In [1]:
a = 'abcd'
b = 'efg'
c = a/b
c

TypeError: unsupported operand type(s) for /: 'str' and 'str'

In [1]:
import os
os.cpu_count()

12

In [4]:
# Program to get a substring from the given string 

a = '1234567'

# stop = 3
# contains 0, 1 and 2 indices
s = slice(None) 
print(s)
a[s]  #  123



slice(None, None, None)


'1234567'

In [1]:
 float("inf")

inf

In [7]:
import torch

a = torch.randn(1,3)
print(a)
a.t()

tensor([[-0.4847,  0.1779, -0.5417]])


tensor([[-0.4847],
        [ 0.1779],
        [-0.5417]])

In [11]:
a = torch.randn(2, 5984383)
b = a.mean(dim = -2, keepdim=True)
print(b.shape)

torch.Size([1, 5984383])


In [8]:
a = 4
if a == 4:
    print('same')
elif a > 3:
    print('bigger')
elif a < 6:
    print('smaller')    
else:
    print('hahaha')        

same


In [3]:
import test
import demucs

init.py


In [10]:
a = {'a':1, 'b':2, 'c':3}
for n, v in a.items():
    print(n, v)
 
b = "  #   "
c = b.join(a)
c

a 1
b 2
c 3


'a  #   b  #   c'

In [3]:
import torch
import torch.nn as nn

lstm = nn.LSTM(bidirectional=True, num_layers=1, hidden_size=5, input_size=5)

x = torch.arange(25).view(5,1,5).float()

o = lstm(x)
print(o[0].shape)
print(o[0])

torch.Size([5, 1, 10])
tensor([[[-9.3224e-02,  2.3400e-02, -4.3446e-02, -1.4609e-01,  9.3889e-02,
          -7.5288e-01, -1.2144e-01, -1.9579e-01, -5.0405e-02, -5.9986e-02]],

        [[ 6.8343e-02,  2.0761e-03, -1.5853e-03,  5.2012e-01,  2.0161e-01,
          -8.8312e-01, -2.7539e-03, -5.2546e-03, -1.2683e-03, -6.5027e-04]],

        [[ 6.5151e-01,  2.4033e-05, -1.0469e-05,  9.1601e-01,  2.8199e-01,
          -8.5313e-01, -4.8830e-05, -9.8070e-05, -2.9384e-05, -5.1912e-06]],

        [[ 7.3809e-01,  4.1052e-08, -5.6949e-08,  9.8815e-01,  3.0230e-01,
          -7.2347e-01, -9.1088e-07, -1.8890e-06, -6.9356e-07, -3.9146e-08]],

        [[ 7.5523e-01,  1.3975e-11, -2.9270e-10,  9.9839e-01,  3.1134e-01,
          -4.4263e-01, -1.7637e-08, -3.1818e-08, -1.6587e-08, -2.9484e-10]]],
       grad_fn=<CatBackward0>)


In [7]:
a = torch.empty(3,3).uniform_(0,1)
a

tensor([[0.4326, 0.7014, 0.0521],
        [0.4432, 0.1396, 0.5436],
        [0.4847, 0.4569, 0.3583]])

In [13]:
a = 0 or 2
print(a)
b = 3 or 4
print(b)

2
3


In [34]:
import musdb
import random

mus = musdb.DB(root = '/home/bj/data/dnn/cfnet_venv/music_data/musdb18')
# print(mus.tracks)
for track in mus:
    print(track.name, track.path )
    print(track.sources)
    print(track.audio.shape)
    print(track.targets, track.targets['vocals'].audio.shape)

    track.chunk_duration = 5.0
    track.chunk_start = random.uniform(0, track.duration - track.chunk_duration)
    x = track.audio.T
    y = track.targets['vocals'].audio.T
    print(x, y)

A Classic Education - NightOwl /home/bj/data/dnn/cfnet_venv/music_data/musdb18/train/A Classic Education - NightOwl.stem.mp4
{'vocals': /home/bj/data/dnn/cfnet_venv/music_data/musdb18/train/A Classic Education - NightOwl.stem.mp4, 'drums': /home/bj/data/dnn/cfnet_venv/music_data/musdb18/train/A Classic Education - NightOwl.stem.mp4, 'bass': /home/bj/data/dnn/cfnet_venv/music_data/musdb18/train/A Classic Education - NightOwl.stem.mp4, 'other': /home/bj/data/dnn/cfnet_venv/music_data/musdb18/train/A Classic Education - NightOwl.stem.mp4}
(7552000, 2)
OrderedDict([('vocals', vocals), ('drums', drums), ('bass', bass), ('other', other), ('accompaniment', bass+drums+other), ('linear_mixture', vocals+bass+drums+other)]) (7552000, 2)
[[-0.01119995 -0.0027771   0.00424194 ... -0.0553894  -0.07116699
  -0.08987427]
 [-0.27740479 -0.26013184 -0.24954224 ... -0.078125   -0.12237549
  -0.16931152]] [[ 0.0682373   0.07260132  0.07543945 ... -0.06079102 -0.07434082
  -0.09103394]
 [ 0.02297974  0.021

In [3]:
sl = slice(1,3)
sl2 = slice(1, None, None)
sl3 = slice(None, None, None)
a = [1,2,3,4,5,6,7,8]
print(a[sl])
print(a[sl2])
print(a[sl3])

[2, 3]
[2, 3, 4, 5, 6, 7, 8]
[1, 2, 3, 4, 5, 6, 7, 8]


In [5]:
def gen():
    for i in range(10):
        yield i
num = gen()

for i in num:
    print(i)        

0
1
2
3
4
5
6
7
8
9
